### ISSUE TITLE
Dépendance data.table

### ISSUE THREAD

**Issue by joelgombin** [observatoire-territoires/migR#3]
La dépendance à `data.table` est lourde, j'ai l'impression que tu ne l'utilises que pour `fread`, es-ce vraiment indispensable ? Peut-être passer `data.table` en `Suggests` et prévoir une possibilité alternative (par exemple via `readr::read_csv`) ?

**Comment by observatoire-territoires** [comment]
Ok fait, on charge dorénavant avec `readr::read_csv` et non plus `data.table::fread`.
